import './src/data/global-ai-evidence.js'
console.log('global-ai-evidence OK')
import './src/data/functions.js'
console.log('functions OK')
import './src/data/use-cases.js'
console.log('use-cases OK')
import './src/data/hero-use-cases.js'
console.log('hero-use-cases OK')
import './src/data/industry-context.js'
console.log('industry-context OK')
import './src/data/frontier-vision.js'
console.log('frontier-vision OK')
import './src/data/customer-stories.js'
console.log('customer-stories OK')
