import type { CustomerStory } from './types';

// Extracted from 40 customer 1-pager PPTXs via PowerPoint COM text extraction
// 40 customer stories with curated industry tags
// Generated by scripts/final_customer_extraction.py

export const CUSTOMER_STORIES: CustomerStory[] = [
  {
    id: 'air-india',
    company: 'Air India',
    industry: 'transportation',
    product: 'Azure OpenAI in Foundry Models',
    storyUrl: 'https://www.microsoft.com/en/customers/story/19768-air-india-azure-open-ai-service',
    challengeIds: ['customer-experience', 'cost-optimization', 'autonomous-systems'],
    keyMetrics: [
      '97% success rate',
      '97% of 4 million',
      '40,000 customer queries daily across more than',
      '1,300 different questions',
      '40,000 daily queries instantly'
    ],
    summary: 'Air India faced a significant challenge as millions of customer queries overwhelmed its support channels, leading to rising costs, slower response times, and growing frustration for both customers and staff. The internal development team began working on an agentic solution, rapidly reaching a viable product that they could improve over time as they analysed interactions. Within six months, AI.g was responding to customers, making Air India the first airline worldwide to deploy generative AI for',
    quotes: [
      'AI.g now handles 97% of 4 million-plus customer queries. We’ve saved millions, but the real win is customers aren’t waiting—they’re served. Fast answers for them, unlocking real problem-solving time for our people.'
    ],
  },
  {
    id: 'akkodis-consulting',
    company: 'AKKODiS Consulting',
    industry: 'professional-services',
    product: 'Microsoft Power Platform',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25896-akkodis-consulting-microsoft-power-platform',
    challengeIds: ['workforce-modernization', 'digital-transformation', 'innovation-speed'],
    keyMetrics: [
      '15,800 hours saved annually through internal process automation'
    ],
    summary: 'AKKODiS Consulting, an engineering and consulting firm, faced the urgent need to adapt to Japan’s aging demographic to support both its own business and its clients. Instead of relying on a top-down approach, AKKODiS deployed Microsoft Power Platform and Microsoft 365 Copilot to its entire field of employees, based on the belief that those closest to the work are best positioned to lead transformation. “By democratizing innovation with Microsoft Power Platform and Copilot, we’re turning Japan’s',
    quotes: [
      'By democratizing innovation with Microsoft Power Platform and Copilot, we’re turning Japan’s demographic challenge into a source of sustainable growth and creativity.'
    ],
  },
  {
    id: 'alaska-airlines',
    company: 'Alaska Airlines',
    industry: 'transportation',
    product: 'Azure OpenAI',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25850-alaska-airlines-azure-openai/',
    challengeIds: ['customer-experience', 'innovation-speed'],
    keyMetrics: [
      '75% of planning time and achieving 90'
    ],
    summary: 'Alaska Airlines identified guests were spending 40-plus hours in planning trips and rarely using AlaskaAir.com’s Where We Fly tool, making travel discovery overwhelming and impersonal. In response, Alaska Airlines launched Alaska Inspires, a natural language search tool that brings the emotion into travel planning. Built with Azure OpenAI in Foundry Models, Alaska Inspires personalizes destination discovery and booking. “Microsoft has been a key partner in delivering our holistic AI strategy. Al',
    quotes: [
      'Microsoft has been a key partner in delivering our holistic AI strategy. Alaska Inspires is a great example of how our teams can quickly build, test, and launch GenAI experiences using Azure OpenAI.'
    ],
  },
  {
    id: 'andritz',
    company: 'ANDRITZ',
    industry: 'manufacturing',
    product: 'Microsoft 365 Copilot',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25831-andritz-microsoft-365-copilot/',
    challengeIds: ['knowledge-management', 'workforce-modernization'],
    keyMetrics: [
      '90% of licensed users actively engaging'
    ],
    summary: 'ANDRITZ faced a critical inflection point as it sought to preserve the deep expertise of its seasoned engineers and employees, many of whom were approaching retirement or transitioning to new roles. Thanks to the seamless integration of Microsoft technologies, including Copilot, Copilot Studio, and Azure AI Foundry, the solution is scalable, easy to use, and ready for rapid deployment across ANDRITZ’s global teams. “The Knowledge Preservation Agent is a great example of how we’re capturing exper',
    quotes: [
      'The Knowledge Preservation Agent is a great example of how we’re capturing expertise at ANDRITZ in a way that’s practical and impactful. It helps teams collect and preserve knowledge from all generations and makes it accessible across the organization.'
    ],
  },
  {
    id: 'bayer',
    company: 'Bayer',
    industry: 'healthcare',
    product: 'Azure Phi',
    storyUrl: 'https://www.microsoft.com/en/customers/story/1703594261178267318-bayer-microsoft-copilot-germany',
    challengeIds: ['field-operations', 'knowledge-management', 'innovation-speed'],
    keyMetrics: [
      '10% productivity gains, with complex questions resolved in under'
    ],
    summary: 'Bayer’s agronomic advisors faced growing complexity in delivering accurate crop protection guidance across diverse products and regulations, with frontline teams spending hours navigating lengthy labels to make critical decisions. Bayer built E.L.Y. Crop Protection (E.L.Y. Mini), a small language model using Microsoft Phi and Azure AI Foundry, fine-tuned on proprietary label data. Through E.L.Y. Mini, it provides precise, compliant answers to Bayer teams and partners. “Bayer’s E.L.Y. Crop Protec',
    quotes: [
      'Bayer’s E.L.Y. Crop Protection (Mini) is like giving a new advisor 20 years of agronomic experience in their back pocket. That kind of speed and confidence is a game changer.'
    ],
  },
  {
    id: 'bmw-ag',
    company: 'BMW AG',
    industry: 'automotive',
    product: 'Azure Database for PostgreSQL',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25683-bmw-ag-azure',
    challengeIds: ['data-analytics', 'innovation-speed', 'autonomous-systems'],
    keyMetrics: [
    ],
    summary: 'BMW modernized its Mobile Data Recorder system with Microsoft Azure, deploying multi-agent AI that makes the 5 to 10 terabytes of test-vehicle data generated each week instantly accessible and actionable for all engineers. “Azure services form the backbone of our multi-agent system, ensuring every engineer benefits from a persistent conversational history—results that remain intact through scaling, restarts, or updates. That level of reliability gives us the confidence to bring AI to hundreds of',
  },
  {
    id: 'broward-county-public-schools',
    company: 'Broward County Public Schools',
    industry: 'education',
    product: 'Microsoft 365 Copilot',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26258-broward-county-public-schools-microsoft-365-copilot',
    challengeIds: ['cost-optimization', 'data-analytics', 'workforce-modernization'],
    keyMetrics: [
      '$90 million',
      '235,000 students across 235 schools',
      '20,000 Microsoft 365 Copilot licenses integrate'
    ],
    summary: 'Broward County Public Schools confronted a $90 million-plus shortfall requiring operational efficiency at scale. Despite being data-rich, the district lacked real-time insights needed to support 235,000 students across 235 schools. The district deployed 20,000 Microsoft 365 Copilot licenses integrated with its Microsoft 365 ecosystem, providing AI capabilities to educators and staff while enabling students to use Copilot Chat and Copilot Studio. “We\'re data rich, but we were poor at creating tha',
    quotes: [
      'We\'re data rich, but we were poor at creating that level of insight necessary to have real-time decision making for real-time impact. We just didn\'t have those capabilities before. But now, with Microsoft 365 Copilot, we can maximize those opportunities.'
    ],
  },
  {
    id: 'commerzbank-ag',
    company: 'Commerzbank AG',
    industry: 'financial-services',
    product: 'Azure HDInsight on Azure Kubernetes Service (AKS)',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25676-commerzbank-ag-azure-ai-foundry-agent-service',
    challengeIds: ['customer-experience', 'security-compliance', 'autonomous-systems'],
    keyMetrics: [
      '75% of requests autonomously and delivering round',
      '30,000 monthly conversations with Foundry Agent'
    ],
    summary: 'Commerzbank AG needed to modernize digital customer support and unify outdated systems while ensuring regulatory compliance, elevated fraud protection, and transparency across every channel. Using Foundry Agent Service, Commerzbank AG built Ava—an AI-powered agent that automates customer interactions through highly secure agentic orchestration, persistent memory, and full compliance. Ava manages 30,000-plus customer conversations every month, resolving 75% of requests autonomously and delivering',
  },
  {
    id: 'conagra-brands',
    company: 'Conagra Brands',
    industry: 'consumer-goods',
    product: 'Microsoft Copilot',
    storyUrl: 'https://www.microsoft.com/en/customers/conagra-brands',
    challengeIds: ['workforce-modernization', 'security-compliance'],
    keyMetrics: [
    ],
    summary: 'Conagra Brands has a well-established culture of embracing technology in service of customers. What’s next for the consumer-packaged goods brand? Introducing AI to the entire workforce through a wildly successful change management program. Conagra Brands takes an employee-led approach to develop new skills with Microsoft Copilot — Tracy Schaefer,Chief Information Officer, Conagra Brands',
    quotes: [
      'Laying the foundation of proper governance, observability, and responsible AI was our first step to engaging our employees with AI. To do that, we built a SteerCo to review risk factors, access, and identity management.'
    ],
  },
  {
    id: 'crowe',
    company: 'Crowe',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26359-crowe-microsoft-365-copilot',
    industry: 'professional-services',
    product: 'Microsoft 365 Copilot',
    challengeIds: ['operational-efficiency', 'knowledge-management', 'autonomous-systems'],
    keyMetrics: [
    ],
    summary: 'Crowe helps clients move from manual lease PDF hunting to audit ready AI—where long, amended, multilingual documents make verification slow and missed terms can increase accounting risk. Crowe built a lease audit AI agent on the Microsoft AI stack—Azure for document understanding and retrieval, plus Copilot Studio and Power Apps to operationalize workflows and integrations with speed to value. Crowe brings audit-ready AI to lease accounting with Copilot Studio and Azure',
    quotes: [
      'Copilot puts AI where the work happens. People are already in Word, Outlook, PowerPoint, and Excel. Use AI in the flow of that work. It’s a little button—you click it, and you’re using it. That’s how it becomes normal.'
    ],
  },
  {
    id: 'csx',
    company: 'CSX',
    storyUrl: 'https://www.microsoft.com/en/customers/story/23950-csx-azure-vmware-solution',
    industry: 'transportation',
    product: 'Microsoft Copilot Studio',
    challengeIds: ['customer-experience', 'supply-chain', 'operational-efficiency'],
    keyMetrics: [
      '1,000+ customers using AI assistant for freight tracking',
      '4,000 AI-powered conversations managed',
      '20,000 route miles optimized with Azure AI'
    ],
    summary: 'CSX wanted to provide customers with a faster way to track freight, manage shipments, and access rail logistics services through its online portal. — Dave Rich, Vice President of Technology Strategy, Architecture, and Governance, CSX CSX boosts supply chain agility using Microsoft Copilot Studio and Microsoft Foundry',
    quotes: [
      'By leveraging Microsoft Copilot Studio and Microsoft Foundry, we accelerated delivery and brought real value to our customers in record time.'
    ],
  },
  {
    id: 'discovery-bank',
    company: 'Discovery Bank',
    storyUrl: 'https://www.microsoft.com/en/customers/story/23562-discovery-bank-azure',
    industry: 'financial-services',
    product: 'Azure OpenAI in Foundry Models',
    challengeIds: ['customer-experience', 'revenue-growth', 'data-analytics'],
    keyMetrics: [
      '50% and improved client satisfaction through real',
      'reduced latency of response times by over 50% and improved client satisfaction through real'
    ],
    summary: 'Discovery Bank needed to scale hyper-personalized financial experiences and deliver faster, smarter client interactions without managing complex infrastructure. Using Azure OpenAI in Foundry Models and Azure Databricks, Discovery Bank built Discovery AI, a generative AI application that powers personalized recommendations for clients and helps service agents tailor their interactions with customers. Discovery AI doubled client engagement with Discovery Bank next best actions. Overall, the AI-pow',
    quotes: [
      'Discovery AI gives every single one of our clients a private banker in their pocket. They can ask questions, receive personalized recommendations, and even perform actions like setting budget reminders.'
    ],
  },
  {
    id: 'emsteel',
    company: 'EMSTEEL',
    industry: 'manufacturing',
    product: 'Microsoft Fabric',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26137-emsteel-microsoft-fabric',
    challengeIds: ['operational-efficiency', 'security-compliance', 'data-analytics'],
    keyMetrics: [
    ],
    summary: 'Fragmented systems and expanding cyber risks slowed vital decisions, strained teams, and hampered efficiency at EMSTEEL, while regulatory and audit demands threatened its agility and competitive edge. The company deployed Microsoft Fabric to unify OT and IT data, Microsoft Foundry for limitless scalability, and Microsoft Entra ID for more secure, flexible access, creating a modern analytics platform. EMSTEEL increased operational efficiency, cut incident response times, reached full compliance,',
    quotes: [
      'Fabric Real-Time Intelligence, Azure Databricks, Fabric Eventhouse, and Microsoft Foundry services are contextualizing and connecting operational data to business decision-making, providing predictive insights and process optimization.'
    ],
  },
  {
    id: 'first-west-credit-union',
    company: 'First West Credit Union',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26016-first-west-credit-union-microsoft-365-copilot',
    industry: 'financial-services',
    product: 'Microsoft 365 Copilot',
    challengeIds: ['workforce-modernization', 'operational-efficiency', 'customer-experience'],
    keyMetrics: [
      '93% employee adoption and a 90'
    ],
    summary: 'First West Credit Union was exploring generative and agentic AI solutions to reduce administrative burden, scale expertise, and enable teams to spend more time supporting members. Customer: First West Credit Union First West Credit Union accelerates service with Microsoft Copilot and AI agents',
    quotes: [
      'I’d call it a productivity boom. Almost every team member at First West has had their Copilot ‘aha’ moment.'
    ],
  },
  {
    id: 'gallagher',
    company: 'Gallagher',
    industry: 'insurance',
    product: 'Microsoft Foundry',
    storyUrl: 'https://www.microsoft.com/en/customers/gallagher',
    challengeIds: ['operational-efficiency', 'security-compliance', 'innovation-speed'],
    keyMetrics: [
      '90% reduction in claims review time',
      'AI platform built on Microsoft Foundry serving 70,000 employees',
      'Automated complex quote workflows across the business'
    ],
    summary: 'Gallagher built its own AI platform on Microsoft Foundry to scale growth in a highly regulated industry. The platform supports secure model execution, Microsoft 365 Copilot enhances daily productivity, and Copilot Studio automates document-heavy processes across 70,000 employees.',
  },
  {
    id: 'heineken',
    company: 'Heineken',
    industry: 'consumer-goods',
    product: 'Microsoft Copilot Studio',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25909-heineken-microsoft-copilot-studio/',
    challengeIds: ['operational-efficiency', 'workforce-modernization', 'digital-transformation'],
    keyMetrics: [
      '7,500 makers',
      '8,000 environments'
    ],
    summary: 'HEINEKEN is a strong digital innovator with thousands of customized applications and automations built on Power Platform by over 7,500 makers. As the number of makers and applications grew, Managed Environments capabilities were deployed, enabling a small product team of just five people to manage over 8,000 environments. Power Platform solutions have contributed 3.1 million hours in increased productivity, while advanced, AI-powered agents on Copilot Studio are supporting both employees and cus',
    quotes: [
      'Managed Environments has greatly simplified and improved our ability to govern Power Platform at scale. It’s the best way to manage at a global level.'
    ],
  },
  {
    id: 'hertz',
    company: 'Hertz',
    industry: 'travel-hospitality',
    product: 'Microsoft Power Platform',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25989-hertz-microsoft-power-platform/',
    challengeIds: ['digital-transformation', 'operational-efficiency'],
    keyMetrics: [
    ],
    summary: 'As part of its technology modernization strategy, Hertz has begun developing low-code applications and agents with Power Platform. Hertz drives process automation and AI-enabled innovation with Power Platform — Zac Cadi,Director, Strategic Technology Initiative, Hertz',
    quotes: [
      'We like how well Power Platform integrates with the Microsoft technologies we already use.'
    ],
  },
  {
    id: 'kbank',
    company: 'KBank',
    industry: 'financial-services',
    product: 'Azure OpenAI in Foundry Models',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26245-kbank-azure-openai-in-foundry-models',
    challengeIds: ['workforce-modernization', 'operational-efficiency'],
    keyMetrics: [
      '50% in some areas, reduced time spent on repetitive tasks, and in',
      '90% of staff wanting to continue using AI across workflows',
      'boosted productivity by up to 50% in some areas'
    ],
    summary: 'KBank faced uneven AI readiness and employee anxiety about AI’s impact on jobs. The challenge was to upskill staff responsibly and turn early AI interest and skepticism into practical, productivity-driven adoption. KBank upskilled its staff by embedding Azure Open AI in daily workflows, evolving tools into agents that automate tasks and boost productivity. “Once the staff got comfortable using the tools and saw how they could transform everyday work, that fear turned into confidence.”',
    quotes: [
      'Once the staff got comfortable using the tools and saw how they could transform everyday work, that fear turned into confidence.'
    ],
  },
  {
    id: 'kone',
    company: 'KONE',
    industry: 'manufacturing',
    product: 'Power Apps',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26034-kone-power-apps/',
    challengeIds: ['digital-transformation', 'workforce-modernization', 'operational-efficiency'],
    keyMetrics: [
      '33% reduction in contract handling time',
      '32,000 applications on Power Platform',
      '54,000 contracts per year processed with AI',
      '3,000 makers enabled'
    ],
    summary: 'KONE, a leader in the elevator and escalator industry, selected Power Platform to help drive its digital transformation and accelerate its development of AI-driven business solutions. “Power Platform makes it easy for our employees to build their own solutions and become more self-reliant.” KONE elevates its automation and AI strategies with Microsoft Power Platform',
    quotes: [
      'Power Platform makes it easy for our employees to build their own solutions and become more self-reliant.'
    ],
  },
  {
    id: 'lc-waikiki',
    company: 'LC Waikiki',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26176-lc-waikiki-dynamics-365-finance/',
    industry: 'retail',
    product: 'Dynamics 365 Finance',
    challengeIds: ['digital-transformation', 'operational-efficiency', 'supply-chain'],
    keyMetrics: [
      '50% while improving self'
    ],
    summary: 'As LC Waikiki grew to 1,300-plus stores and over 1 million daily transactions, it needed to modernize its long‑standing Dynamics AX and adopt a unified, scalable ERP to manage complex global operations. LC Waikiki implemented Dynamics 365 Finance and Supply Chain Management and used Power BI and Power Platform plus Copilot Studio agents like FinChat to enable web-based workflows, automation, and conversational self-service in Finance. LC Waikiki automated high-volume processes and improved repor',
    quotes: [
      'This transformation is a key step toward building an intelligent and connected enterprise—where data, technology, and strategy converge to shape more agile, resilient, and future-ready business models.'
    ],
  },
  {
    id: 'lseg',
    company: 'LSEG',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25709-lseg-microsoft-fabric',
    industry: 'financial-services',
    product: 'Microsoft Fabric',
    challengeIds: ['data-analytics', 'digital-transformation', 'innovation-speed'],
    keyMetrics: [
      '1,200 datasets'
    ],
    summary: 'Global finance depends on accurate, trusted data. LSEG, partner to top financial institutions, wanted to simplify its complex, fragmented data landscape to deliver a consistent, unified experience and reduce the time to create new data products. Using Microsoft Fabric, LSEG is building a unified data platform, consolidating 30 systems, 1,200 datasets, and 33 petabytes of data to accelerate product development, improve data quality, and enable AI readiness. LSEG reduced product development timeli',
    quotes: [
      'Partnering with Microsoft gives us confidence in long-term innovation and investment. This strategic collaboration goes beyond a vendor relationship, enabling co-innovation and shared learning.'
    ],
  },
  {
    id: 'meo',
    company: 'MEO',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26174-meo-azure',
    industry: 'telecommunications',
    product: 'Azure',
    challengeIds: ['customer-experience', 'operational-efficiency', 'innovation-speed'],
    keyMetrics: [
    ],
    summary: 'MEO aimed to stay ahead as the telecom market evolved—while continuing to improve customer experience and operational efficiency. MEO built a modular “AI factory” on Azure and launched a real-time AI assistant that gives technicians instant, governed network insights. “We\'re already seeing the benefits of deploying new use cases more rapidly than expected to other operational components like, for instance, planned interventions and disaster recovery impacts.”',
    quotes: [
      'We\'re already seeing the benefits of deploying new use cases more rapidly than expected to other operational components like, for instance, planned interventions and disaster recovery impacts.'
    ],
  },
  {
    id: 'microsoft-copilot-studio',
    company: 'Microsoft',
    industry: 'technology',
    product: 'Microsoft Copilot Studio',
    challengeIds: ['operational-efficiency', 'innovation-speed'],
    keyMetrics: [
      '61% lower latency and up to 70% cost reduction in AI operations'
    ],
    summary: '“Working with Copilot Studio made it easy to scale a low-code solution across Microsoft properties without technical overhead or custom development.” — Selva Sankaran,Principal Software Engineering Manager, Microsoft',
    quotes: [
      'Working with Copilot Studio made it easy to scale a low-code solution across Microsoft properties without technical overhead or custom development.'
    ],
  },
  {
    id: 'microsoft-foundry',
    company: 'Microsoft',
    industry: 'technology',
    product: 'Microsoft Foundry',
    challengeIds: ['revenue-growth', 'data-analytics', 'customer-experience'],
    keyMetrics: [
      '$10M in value',
      '100,000+ customer voice inputs embedded into marketing workflows'
    ],
    summary: 'To make that possible, Microsoft built the AI Messaging Assistant (AMA), a generative AI application grounded in 100,000+ customer voice inputs embedded into marketing workflows customer voice intelligence directly into marketing workflows, delivering structured insights in real time. The result is a growth engine. Customer intelligence now reaches decisions that were previously out of range, delivering approximately $10M in value. — Romani Patel, Principal Product Lead, Microsoft',
    quotes: [
      'Customer intelligence creates advantage when it compounds. That requires it to operate as a strategic, repeatable asset—moving beyond one-time reports to become a trusted, continuously accessible input embedded directly in marketing workflow.'
    ],
  },
  {
    id: 'microsoft-sustainability',
    company: 'Microsoft',
    industry: 'technology',
    product: 'Microsoft Power Platform',
    challengeIds: ['sustainability', 'digital-transformation'],
    keyMetrics: [
      '94% reduction in sustainability reporting effort'
    ],
    summary: '“Sustainability Manager was built on the goodness of Power Platform, making it extensible for our customers to customize - and our partners to deliver their own native solutions.” — Sai Koduri,Senior Product Manager for Sustainability Manager, Microsoft',
    quotes: [
      'Sustainability Manager was built on the goodness of Power Platform, making it extensible for our customers to customize - and our partners to deliver their own native solutions.'
    ],
  },
  {
    id: 'morningstar-inc',
    company: 'Morningstar Inc',
    industry: 'financial-services',
    product: 'Microsoft Copilot',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26333-morningstar-inc-microsoft-copilot',
    challengeIds: ['data-analytics', 'workforce-modernization', 'customer-experience'],
    keyMetrics: [
      '30% of their day on manual portfolio reviews, meeting preparation'
    ],
    summary: '“Microsoft Copilot and Copilot Studio create a powerful ecosystem. It’s plug-and-play access. You can connect tools that fuel the full advisor lifecycle with AI, creating agents to support discovery and research, portfolio construction, monitoring, and client communication, while grounding AI workflows in trusted data, research, and investment IP.” With Microsoft 365 Copilot as the entry point, Morningstar integrated its data through Model Context Protocol (MCP) and Microsoft Copilot Studio, ena',
  },
  {
    id: 'mtr-corporation',
    company: 'MTR Corporation',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26104-mtr-corporation-microsoft-365-copilot/',
    industry: 'transportation',
    product: 'Microsoft 365 Copilot',
    challengeIds: ['customer-experience', 'workforce-modernization', 'operational-efficiency'],
    keyMetrics: [
    ],
    summary: 'MTR adopted Microsoft 365 Copilot to automate drafting, summarisation, and analysis in Microsoft 365 apps, while Power Platform enabled governed, low‑code solutions and role‑based copilots to support daily workflows across the organisation. “We are committed to transforming customer experience through innovative technology. With the help of technology, AI Tracy provides instant and reliable support to passengers, making their journeys hassle-free.” Keeping Cities Moving: How MTR Corporation Elev',
    quotes: [
      'We are committed to transforming customer experience through innovative technology. With the help of technology, AI Tracy provides instant and reliable support to passengers, making their journeys hassle-free.'
    ],
  },
  {
    id: 'network-rail',
    company: 'Network Rail',
    industry: 'transportation',
    product: 'Power Apps',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26368-network-rail-power-apps',
    challengeIds: ['workforce-modernization', 'digital-transformation', 'field-operations'],
    keyMetrics: [
      '10x faster development cycles',
      '2,500 makers to build innovative business solu'
    ],
    summary: 'Network Rail wanted a more flexible development platform to help digitize processes, empower frontline workers, and foster a culture of innovation. “Our employees know the business better than anyone. Empowering these employees to address their own business challenges with Power Platform just makes good business sense.” Network Rail empowers over 2,500 makers to build innovative business solutions with Power Platform and Copilot Studio',
    quotes: [
      'Our employees know the business better than anyone. Empowering these employees to address their own business challenges with Power Platform just makes good business sense.'
    ],
  },
  {
    id: 'niq',
    company: 'NIQ',
    industry: 'consumer-goods',
    product: 'Microsoft Foundry',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25893-niq-microsoft-foundry/',
    challengeIds: ['operational-efficiency', 'innovation-speed', 'data-analytics'],
    keyMetrics: [
      'cut item coding time by 90%'
    ],
    summary: 'NIQ’s manual item coding—extracting structured product data from packaging images—was limiting scalability. The company sought an automated solution to accelerate insights and cut operational costs. NIQ used Microsoft Foundry—Azure OpenAI in Foundry Tools, Azure Document Intelligence in Foundry Tools, and Azure AI Search—to build Capture as a Service (CaaS), automating item coding for faster, more accurate, and scalable product data coding. With Foundry, NIQ cut item coding time by 90%, expands',
    quotes: [
      'Foundry gives our data scientists the appropriate oversight capabilities to ensure our CaaS quality standards remain the highest in the industry—critical to our clients making strategic decisions based on our data.'
    ],
  },
  {
    id: 'puerto-rico-department-of-education',
    company: 'Puerto Rico Department of Education',
    industry: 'education',
    product: 'Microsoft 365 Copilot',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25724-puerto-rico-department-of-education-microsoft-intune',
    challengeIds: ['digital-transformation', 'workforce-modernization', 'security-compliance'],
    keyMetrics: [
    ],
    summary: 'Copilot enabled teachers to quickly tailor activities to diverse learner needs, improving differentiation and freeing time for higher impact interactions. “The pandemic highlighted the limitations of our existing systems. We urgently needed a modern, integrated solution to support remote learning and safeguard sensitive information.” Customer: Puerto Rico Department of Education',
    quotes: [
      'The pandemic highlighted the limitations of our existing systems. We urgently needed a modern, integrated solution to support remote learning and safeguard sensitive information.'
    ],
  },
  {
    id: 'pwc',
    company: 'PwC',
    industry: 'professional-services',
    product: 'Microsoft 365 Enterprise',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26160-pwc-microsoft-365-enterprise',
    challengeIds: ['workforce-modernization', 'cost-optimization', 'digital-transformation'],
    keyMetrics: [
      '$25 million in savings from consolidating platforms, and',
      '$150 million in time savings from Copilot use, returning valua',
      '$150M',
      '364,000 people across 130'
    ],
    summary: 'With more than 364,000 people across 130-plus countries, PwC is a superpower whose size can also slow change, entrench silos, and make it harder to move as one. To stay ahead, the firm needs to modernize how its people work together. PwC rolled out Microsoft 365 with Copilot across the entire firm, providing secure, intuitive tools powered by AI to every employee. The migration unified global teams and enabled country-specific configurations. PwC modernizes across 136 countries via Microsoft 365',
    quotes: [
      'We’re evolving into an AI first organization—embedding Microsoft 365 with Copilot so our people can spend more time advising clients and less time on administrative work.'
    ],
  },
  {
    id: 'sjr',
    company: 'SJR',
    industry: 'media',
    product: 'Azure AI Foundry',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25742-sjr-azure-ai-foundry/',
    challengeIds: ['innovation-speed', 'customer-experience', 'data-analytics'],
    keyMetrics: [
    ],
    summary: 'SJR built GX Manager with Microsoft Foundry and Azure Content Understanding in Foundry Tools to automate enrichment and image matching. The modular pipeline runs in parallel, connects seamlessly with existing systems, and keeps developers in control. — Allan Mazzocchi, Lead Product Manager, SJR Developer Spotlight: How SJR modernizes website personalization with Foundry',
    quotes: [
      'We measured onboarding speed, tracked error reduction after enrichment, and logged throughput on ingestion jobs. These metrics grounded our decisions and built credibility.'
    ],
  },
  {
    id: 'sjr-personalization',
    company: 'SJR',
    industry: 'media',
    product: 'Azure AI Foundry',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25742-sjr-azure-ai-foundry/',
    challengeIds: ['innovation-speed', 'customer-experience'],
    keyMetrics: [
    ],
    summary: 'SJR is setting a new industry benchmark for digital personalization, driving transformation across web experiences with its first-to-market AI solution, Generative Experience (GX) Manager. — Selena Cameron, Global CEO, SJR SJR modernizes websites with Foundry-powered personalization',
    quotes: [
      'Our collaboration with Microsoft made GX Manager more than a website upgrade. It helped us deliver a paradigm shift in digital marketing that has opened new possibilities for intelligent content that drives conversion.'
    ],
  },
  {
    id: 'swiss-post',
    company: 'Swiss Post',
    industry: 'transportation',
    product: 'Microsoft 365 Copilot',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25880-swiss-post-microsoft-365-copilot/',
    challengeIds: ['workforce-modernization', 'operational-efficiency'],
    keyMetrics: [
    ],
    summary: 'To sustain excellence in service delivery and meet rising expectations, Swiss Post set out to reimagine how work happens across every team and department. Partnering with Campana & Schott and Microsoft, Swiss Post launched one of the most ambitious and inclusive AI adoption programs in the public sector, empowering a uniquely diverse workforce that includes both frontline workers and administrative teams. Together, Swiss Post, Campana & Schott, and Microsoft have delivered measurable results tha',
  },
  {
    id: 'toyota-leasing-thailand',
    company: 'Toyota Leasing Thailand',
    industry: 'financial-services',
    product: 'Microsoft Copilot for Security',
    storyUrl: 'https://www.microsoft.com/en/customers/story/25882-toyota-leasing-thailand-microsoft-security-copilot/',
    challengeIds: ['security-compliance', 'risk-management'],
    keyMetrics: [
    ],
    summary: 'Phishing attacks and manual reporting strained Toyota Leasing Thailand’s SOC. The team needed faster triage, clearer collaboration, and stronger Zero Trust alignment. — Kalunyu Sopha, Security Manager, Toyota Leasing Thailand Toyota Leasing Thailand improves collaboration, reduces risk, and better protects customers with Security Copilot',
    quotes: [
      'We turned to Microsoft Security Copilot because it integrates with our Microsoft stack. Analysts can ask questions in human language and get context they can act on, which speeds up the handoff between the SOC and our IT team.'
    ],
  },
  {
    id: 'unifi',
    company: 'Unifi',
    industry: 'transportation',
    product: 'Microsoft Copilot Studio',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26265-unifi-microsoft-copilot-studio',
    challengeIds: ['operational-efficiency', 'knowledge-management', 'cost-optimization'],
    keyMetrics: [
    ],
    summary: 'As Unifi quickly grew to become North America’s largest provider of aviation ground handling services, the company was spending more and more time manually processing and reviewing documents, including contracts. Copilot Studio and Power Platform were selected to solve a problem that the company had not been able to address with other AI platforms: process and analyze large files full of specialized industry and legal terms and enable precise, natural language search by Unifi’s legal team. “Our',
    quotes: [
      'Our AI-driven, contract management solution built on Power Platform and Copilot Studio delivers the same performance as off-the-shelf products costing 30 times more.'
    ],
  },
  {
    id: 'virtua-health',
    company: 'Virtua Health',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26318-virtua-health-microsoft-copilot/',
    industry: 'healthcare',
    product: 'Microsoft Copilot',
    challengeIds: ['patient-outcomes', 'data-analytics', 'workforce-modernization'],
    keyMetrics: [
      'improved sepsis identification by 80%'
    ],
    summary: 'Virtua Health sought a secure, scalable way to use its data better to improve patient outcomes, empower staff, and boost efficiency. Virtua Health presents AI-powered data insights to clinicians and operational leaders at the point at which it’s needed to reduce cognitive load on staff and improve patient outcomes. Virtua Health innovates to improve patient care using Copilot as the UI to AI',
    quotes: [
      'The Microsoft suite of products today is really exciting.'
    ],
  },
  {
    id: 'wipro',
    company: 'Wipro',
    industry: 'technology',
    product: 'Microsoft 365 Copilot',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26393-wipro-microsoft-365-copilot/',
    challengeIds: ['workforce-modernization', 'knowledge-management'],
    keyMetrics: [
    ],
    summary: 'Wipro faced uneven employee recognition, limited manager bandwidth, and manual HR audits, with fragmented systems making it hard to surface insights and act in the flow of work across enterprise platforms. Wipro embedded the Vantage Circle agent into Microsoft 365 Copilot, integrating Copilot with enterprise data and workflows, including Dynamics 365, to enable in-the-flow AI-driven employee recognition. With Copilot-powered insights and automation, Wipro improved recognition consistency, increa',
    quotes: [
      'For employees, recognition should feel natural, not delayed or transactional. Bringing Winner’s Circle into Microsoft 365 Copilot allows appreciation to happen in real time, rooted in everyday collaboration, which strengthens both engagement and trust.'
    ],
  },
  {
    id: 'wsp',
    company: 'WSP',
    industry: 'professional-services',
    product: 'Microsoft 365 Copilot',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26012-wsp-microsoft-365-copilot/',
    challengeIds: ['workforce-modernization', 'innovation-speed', 'digital-transformation'],
    keyMetrics: [
      '$1 billion strategic partnership with Microsoft, including e',
      '75,000 professionals who wake up every morning'
    ],
    summary: 'WSP, one of the world’s leading professional services firms, set out to be a catalyst for modernization in the Architecture, Engineering, and Construction (AEC) industry. To achieve this, WSP entered a seven-year, $1 billion strategic partnership with Microsoft, including expanding Microsoft 365 Copilot across its global workforce to empower tens of thousands of engineers and scientists. As a result, WSP’s Copilot users have reported higher productivity and there is potential for accelerated pro',
  },
  {
    id: 'yara-international',
    company: 'Yara International',
    industry: 'energy',
    product: 'Azure',
    storyUrl: 'https://www.microsoft.com/en/customers/story/26373-yara-international-azure',
    challengeIds: ['operational-efficiency', 'field-operations', 'data-analytics', 'risk-management'],
    keyMetrics: [
      '70% faster resolution time after shutdown, reduced field trips by',
      '50% in specific engineering tasks',
      'achieved up to 70% faster resolution time after shutdown',
      'reduced field trips by 60%',
      'increased efficiency by 50% in specific engineering tasks'
    ],
    summary: 'Yara International, a global fertilizer and chemicals company, runs many projects and complex plants that generate vital data. But the company lacked efficient tools to find and validate the data, making more work for the production team. To reduce operational risk, Yara worked with Kongsberg Digital to deploy a digital twin (Kognitwin), running on Azure, that unifies plant, equipment, and engineering data into a single, secure, remote view, enabling faster, safety-critical decisions. By consoli',
    quotes: [
      'We looked at the usual cloud options, but we chose Azure because it’s the one platform that holds security, identity, hybrid, and AI together in a way that actually fits industrial reality.'
    ],
  }
    ];